export type UISchema = {
  type?: string;
  title?: string;
  'x-form-title'?: string;
  description?: string;
  'x-form-info'?: string;
  properties?: Record<string, UISchema>;
  items?: UISchema;
  required?: string[];
  minItems?: number;
  maxItems?: number;
  minimum?: number;
  maximum?: number;
  pattern?: string;
  enum?: string[];
  examples?: unknown[];
  format?: string;
  default?: unknown;
  readOnly?: boolean;
  writeOnly?: boolean;
  additionalProperties?: UISchema;
  'x-multi-language'?: boolean;
  'x-range'?: boolean;
  'x-file-upload'?: boolean;
  'x-file-content-type-suggestions'?: string[];
  'x-content-type-pattern'?: string;
  'x-file-accept'?: string[];
  'x-reference'?: boolean;
  'x-entity'?: boolean;
  'x-relationship'?: boolean;
  'x-annotated-relationship'?: boolean;
  'x-readonly'?: boolean;
  'x-blob'?: boolean;
  'x-either-or'?: string;
  'x-form-choices'?: string[];
  'x-form-url'?: string;
  'x-required-languages'?: string[];
  'x-allowed-range'?: string;
  'x-allowed-value'?: string;
  'x-allowed-id-short'?: string[];
  'x-edit-id-short'?: boolean;
  'x-naming'?: string;
  'x-unresolved-definition'?: boolean;
  'x-unresolved-reason'?: string;
  'x-resolution'?: Record<string, unknown>;
  'x-order'?: number;
};
