export type UISchema = {
  type?: string;
  title?: string;
  description?: string;
  properties?: Record<string, UISchema>;
  items?: UISchema;
  required?: string[];
  minItems?: number;
  minimum?: number;
  maximum?: number;
  pattern?: string;
  enum?: string[];
  format?: string;
  default?: unknown;
  readOnly?: boolean;
  writeOnly?: boolean;
  additionalProperties?: UISchema;
  'x-multi-language'?: boolean;
  'x-range'?: boolean;
  'x-file-upload'?: boolean;
  'x-reference'?: boolean;
  'x-entity'?: boolean;
  'x-relationship'?: boolean;
  'x-annotated-relationship'?: boolean;
  'x-readonly'?: boolean;
  'x-blob'?: boolean;
  'x-form-url'?: string;
  'x-required-languages'?: string[];
  'x-allowed-range'?: string;
};
