/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Health Check */
    get: operations["health_check_health_get"];
  };
  "/api/v1/tenants/mine": {
    /**
     * List My Tenants
     * @description List tenants the current user belongs to.
     */
    get: operations["list_my_tenants_api_v1_tenants_mine_get"];
  };
  "/api/v1/tenants": {
    /**
     * List Tenants
     * @description List all tenants (platform admin).
     */
    get: operations["list_tenants_api_v1_tenants_get"];
    /**
     * Create Tenant
     * @description Create a new tenant (platform admin).
     */
    post: operations["create_tenant_api_v1_tenants_post"];
  };
  "/api/v1/tenants/{tenant_slug}": {
    /**
     * Get Tenant
     * @description Get tenant details (tenant member).
     */
    get: operations["get_tenant_api_v1_tenants__tenant_slug__get"];
    /**
     * Update Tenant
     * @description Update tenant metadata (platform admin).
     */
    patch: operations["update_tenant_api_v1_tenants__tenant_slug__patch"];
  };
  "/api/v1/tenants/{tenant_slug}/members": {
    /**
     * List Members
     * @description List members of a tenant (tenant admin).
     */
    get: operations["list_members_api_v1_tenants__tenant_slug__members_get"];
    /**
     * Add Member
     * @description Add a member to a tenant (tenant admin).
     */
    post: operations["add_member_api_v1_tenants__tenant_slug__members_post"];
  };
  "/api/v1/tenants/{tenant_slug}/members/{user_subject}": {
    /**
     * Remove Member
     * @description Remove a member from a tenant (tenant admin).
     */
    delete: operations["remove_member_api_v1_tenants__tenant_slug__members__user_subject__delete"];
  };
  "/api/v1/templates/{template_key}/definition": {
    /**
     * Get Template Definition
     * @description Get the template definition AST (BaSyx parsed).
     *
     * Returns a stable representation of the submodel template tree.
     */
    get: operations["get_template_definition_api_v1_templates__template_key__definition_get"];
  };
  "/api/v1/templates": {
    /**
     * List Templates
     * @description List all registered templates.
     *
     * Returns all DPP4.0 templates that have been fetched and cached.
     */
    get: operations["list_templates_api_v1_templates_get"];
  };
  "/api/v1/templates/{template_key}": {
    /**
     * Get Template
     * @description Get a specific template by key.
     *
     * Optionally specify a version, otherwise returns the pinned version.
     */
    get: operations["get_template_api_v1_templates__template_key__get"];
  };
  "/api/v1/templates/{template_key}/schema": {
    /**
     * Get Template Ui Schema
     * @description Get the UI schema for a template.
     *
     * Returns a JSON Schema compatible structure for form rendering.
     */
    get: operations["get_template_ui_schema_api_v1_templates__template_key__schema_get"];
  };
  "/api/v1/templates/refresh": {
    /**
     * Refresh Templates
     * @description Refresh all templates from IDTA repository.
     *
     * Requires publisher role. Fetches and updates all DPP4.0 templates.
     */
    post: operations["refresh_templates_api_v1_templates_refresh_post"];
  };
  "/api/v1/templates/refresh/{template_key}": {
    /**
     * Refresh Template
     * @description Refresh a specific template from IDTA repository.
     *
     * Requires publisher role.
     */
    post: operations["refresh_template_api_v1_templates_refresh__template_key__post"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps": {
    /**
     * List Dpps
     * @description List DPPs accessible to the current user.
     *
     * Publishers see their own DPPs. Viewers see all published DPPs.
     */
    get: operations["list_dpps_api_v1_tenants__tenant_slug__dpps_get"];
    /**
     * Create Dpp
     * @description Create a new Digital Product Passport.
     *
     * Requires publisher role. Creates a draft DPP with selected templates.
     */
    post: operations["create_dpp_api_v1_tenants__tenant_slug__dpps_post"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps/import": {
    /**
     * Import Dpp
     * @description Import a DPP from a JSON payload.
     *
     * Accepts a raw AAS environment JSON or an export payload with `aasEnvironment`.
     * Optionally validates against a released master version.
     */
    post: operations["import_dpp_api_v1_tenants__tenant_slug__dpps_import_post"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps/rebuild-all": {
    /**
     * Rebuild All Dpps
     * @description Refresh templates and rebuild submodels for all DPPs.
     *
     * Requires tenant admin role.
     */
    post: operations["rebuild_all_dpps_api_v1_tenants__tenant_slug__dpps_rebuild_all_post"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps/{dpp_id}": {
    /**
     * Get Dpp
     * @description Get a specific DPP by ID.
     *
     * Returns full DPP details including current revision AAS environment.
     */
    get: operations["get_dpp_api_v1_tenants__tenant_slug__dpps__dpp_id__get"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps/{dpp_id}/submodel": {
    /**
     * Update Submodel
     * @description Update a submodel within a DPP.
     *
     * Creates a new revision with the updated data.
     */
    put: operations["update_submodel_api_v1_tenants__tenant_slug__dpps__dpp_id__submodel_put"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps/{dpp_id}/submodels/{template_key}/definition": {
    /**
     * Get Submodel Definition
     * @description Get a submodel definition derived from a DPP revision environment.
     */
    get: operations["get_submodel_definition_api_v1_tenants__tenant_slug__dpps__dpp_id__submodels__template_key__definition_get"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps/{dpp_id}/publish": {
    /**
     * Publish Dpp
     * @description Publish a DPP, making it visible to viewers.
     */
    post: operations["publish_dpp_api_v1_tenants__tenant_slug__dpps__dpp_id__publish_post"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps/{dpp_id}/archive": {
    /**
     * Archive Dpp
     * @description Archive a DPP, marking it as no longer active.
     */
    post: operations["archive_dpp_api_v1_tenants__tenant_slug__dpps__dpp_id__archive_post"];
  };
  "/api/v1/tenants/{tenant_slug}/dpps/{dpp_id}/revisions": {
    /**
     * List Revisions
     * @description List all revisions for a DPP.
     *
     * Requires publisher role and ownership.
     */
    get: operations["list_revisions_api_v1_tenants__tenant_slug__dpps__dpp_id__revisions_get"];
  };
  "/api/v1/tenants/{tenant_slug}/masters": {
    /** List Masters */
    get: operations["list_masters_api_v1_tenants__tenant_slug__masters_get"];
    /** Create Master */
    post: operations["create_master_api_v1_tenants__tenant_slug__masters_post"];
  };
  "/api/v1/tenants/{tenant_slug}/masters/{master_id}": {
    /** Get Master */
    get: operations["get_master_api_v1_tenants__tenant_slug__masters__master_id__get"];
    /** Update Master */
    patch: operations["update_master_api_v1_tenants__tenant_slug__masters__master_id__patch"];
  };
  "/api/v1/tenants/{tenant_slug}/masters/{master_id}/versions": {
    /** Release Master Version */
    post: operations["release_master_version_api_v1_tenants__tenant_slug__masters__master_id__versions_post"];
  };
  "/api/v1/tenants/{tenant_slug}/masters/{master_id}/versions/{version}/aliases": {
    /** Update Master Aliases */
    patch: operations["update_master_aliases_api_v1_tenants__tenant_slug__masters__master_id__versions__version__aliases_patch"];
  };
  "/api/v1/tenants/{tenant_slug}/masters/by-product/{product_id}/versions/{version}/template": {
    /** Get Template By Product */
    get: operations["get_template_by_product_api_v1_tenants__tenant_slug__masters_by_product__product_id__versions__version__template_get"];
  };
  "/api/v1/tenants/{tenant_slug}/masters/by-product/{product_id}/versions/{version}/variables": {
    /** Get Variables By Product */
    get: operations["get_variables_by_product_api_v1_tenants__tenant_slug__masters_by_product__product_id__versions__version__variables_get"];
  };
  "/api/v1/tenants/{tenant_slug}/policies": {
    /**
     * List Policies
     * @description List all policies.
     *
     * Requires publisher role. Can filter by DPP ID or policy type.
     */
    get: operations["list_policies_api_v1_tenants__tenant_slug__policies_get"];
    /**
     * Create Policy
     * @description Create a new policy.
     *
     * Requires admin role.
     */
    post: operations["create_policy_api_v1_tenants__tenant_slug__policies_post"];
  };
  "/api/v1/tenants/{tenant_slug}/policies/{policy_id}": {
    /**
     * Get Policy
     * @description Get a specific policy by ID.
     */
    get: operations["get_policy_api_v1_tenants__tenant_slug__policies__policy_id__get"];
    /**
     * Delete Policy
     * @description Delete a policy.
     *
     * Requires admin role.
     */
    delete: operations["delete_policy_api_v1_tenants__tenant_slug__policies__policy_id__delete"];
  };
  "/api/v1/tenants/{tenant_slug}/connectors": {
    /**
     * List Connectors
     * @description List all connectors.
     *
     * Requires publisher role.
     */
    get: operations["list_connectors_api_v1_tenants__tenant_slug__connectors_get"];
    /**
     * Create Connector
     * @description Create a new Catena-X connector.
     *
     * Config should include:
     * - dtr_base_url: DTR API base URL
     * - auth_type: "oidc" or "token"
     * - client_id, client_secret (for OIDC)
     * - token (for token auth)
     * - bpn: Business Partner Number
     * - submodel_base_url: URL where submodels are exposed
     * - edc_dsp_endpoint: Optional EDC DSP endpoint
     */
    post: operations["create_connector_api_v1_tenants__tenant_slug__connectors_post"];
  };
  "/api/v1/tenants/{tenant_slug}/connectors/{connector_id}": {
    /**
     * Get Connector
     * @description Get a specific connector by ID.
     */
    get: operations["get_connector_api_v1_tenants__tenant_slug__connectors__connector_id__get"];
  };
  "/api/v1/tenants/{tenant_slug}/connectors/{connector_id}/test": {
    /**
     * Test Connector
     * @description Test connectivity for a connector.
     *
     * Verifies DTR endpoint is reachable and authentication is valid.
     */
    post: operations["test_connector_api_v1_tenants__tenant_slug__connectors__connector_id__test_post"];
  };
  "/api/v1/tenants/{tenant_slug}/connectors/{connector_id}/publish/{dpp_id}": {
    /**
     * Publish Dpp To Connector
     * @description Publish a DPP to a connector's Digital Twin Registry.
     *
     * The DPP must be published first. Creates or updates
     * the shell descriptor in the DTR.
     */
    post: operations["publish_dpp_to_connector_api_v1_tenants__tenant_slug__connectors__connector_id__publish__dpp_id__post"];
  };
  "/api/v1/tenants/{tenant_slug}/export/{dpp_id}": {
    /**
     * Export Dpp
     * @description Export a DPP in the specified format.
     *
     * Supported formats:
     * - json: AAS Environment JSON with metadata
     * - aasx: AASX package (IDTA Part 5 compliant)
     * - pdf: PDF summary
     */
    get: operations["export_dpp_api_v1_tenants__tenant_slug__export__dpp_id__get"];
  };
  "/api/v1/tenants/{tenant_slug}/qr/{dpp_id}": {
    /**
     * Generate Qr Code
     * @description Generate a QR code for a DPP.
     *
     * The QR code contains the DPP viewer URL for product identification.
     */
    get: operations["generate_qr_code_api_v1_tenants__tenant_slug__qr__dpp_id__get"];
  };
  "/api/v1/tenants/{tenant_slug}/qr/{dpp_id}/carrier": {
    /**
     * Generate Carrier
     * @description Generate a customized data carrier for a DPP.
     *
     * Supports QR codes and GS1 Digital Link format with configurable
     * colors, size, and output format (PNG, SVG, PDF).
     */
    post: operations["generate_carrier_api_v1_tenants__tenant_slug__qr__dpp_id__carrier_post"];
  };
  "/api/v1/tenants/{tenant_slug}/qr/{dpp_id}/gs1": {
    /**
     * Get Gs1 Digital Link
     * @description Get the GS1 Digital Link URL for a DPP.
     *
     * Returns the GS1 Digital Link format URL that can be encoded
     * in a QR code for EU DPP/ESPR compliance.
     */
    get: operations["get_gs1_digital_link_api_v1_tenants__tenant_slug__qr__dpp_id__gs1_get"];
  };
  "/api/v1/admin/settings/global-asset-id-base-uri": {
    /**
     * Get Global Asset Id Base Uri
     * @description Get the current global asset ID base URI.
     *
     * Requires admin role.
     */
    get: operations["get_global_asset_id_base_uri_api_v1_admin_settings_global_asset_id_base_uri_get"];
    /**
     * Update Global Asset Id Base Uri
     * @description Update the global asset ID base URI.
     *
     * Requires admin role.
     */
    put: operations["update_global_asset_id_base_uri_api_v1_admin_settings_global_asset_id_base_uri_put"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AssetIdsInput
     * @description Input model for asset identifiers.
     */
    AssetIdsInput: {
      /** Manufacturerpartid */
      manufacturerPartId: string;
      /** Serialnumber */
      serialNumber?: string | null;
      /** Batchid */
      batchId?: string | null;
      /** Globalassetid */
      globalAssetId?: string | null;
    };
    /**
     * BulkRebuildError
     * @description Response model for rebuild errors.
     */
    BulkRebuildError: {
      /**
       * Dpp Id
       * Format: uuid
       */
      dpp_id: string;
      /** Error */
      error: string;
    };
    /**
     * BulkRebuildResponse
     * @description Response model for bulk rebuild results.
     */
    BulkRebuildResponse: {
      /** Total */
      total: number;
      /** Updated */
      updated: number;
      /** Skipped */
      skipped: number;
      /** Errors */
      errors: components["schemas"]["BulkRebuildError"][];
    };
    /**
     * CarrierFormat
     * @description Supported data carrier formats.
     * @enum {string}
     */
    CarrierFormat: "qr" | "gs1_qr" | "datamatrix";
    /**
     * CarrierOutputType
     * @description Supported output formats.
     * @enum {string}
     */
    CarrierOutputType: "png" | "svg" | "pdf";
    /**
     * CarrierRequest
     * @description Request model for generating a data carrier.
     */
    CarrierRequest: {
      /**
       * @description Type of data carrier to generate
       * @default qr
       */
      format?: components["schemas"]["CarrierFormat"];
      /**
       * Size
       * @description Image size in pixels
       * @default 400
       */
      size?: number;
      /**
       * @description Output file format
       * @default png
       */
      output_type?: components["schemas"]["CarrierOutputType"];
      /**
       * Background Color
       * @description Background color in hex format
       * @default #FFFFFF
       */
      background_color?: string;
      /**
       * Foreground Color
       * @description Foreground (code) color in hex format
       * @default #000000
       */
      foreground_color?: string;
      /**
       * Include Logo
       * @description Whether to embed a logo in the center
       * @default false
       */
      include_logo?: boolean;
      /**
       * Include Text
       * @description Whether to include product ID text below the code
       * @default true
       */
      include_text?: boolean;
    };
    /**
     * CarrierResponse
     * @description Response model for carrier generation metadata.
     */
    CarrierResponse: {
      /**
       * Dpp Id
       * Format: uuid
       */
      dpp_id: string;
      format: components["schemas"]["CarrierFormat"];
      output_type: components["schemas"]["CarrierOutputType"];
      /**
       * Url
       * @description URL encoded in the carrier
       */
      url: string;
      /**
       * Gs1 Digital Link
       * @description GS1 Digital Link if gs1_qr format
       */
      gs1_digital_link?: string | null;
    };
    /**
     * ConnectorCreateRequest
     * @description Request model for creating a connector.
     */
    ConnectorCreateRequest: {
      /** Name */
      name: string;
      /** Config */
      config: {
        [key: string]: unknown;
      };
    };
    /**
     * ConnectorListResponse
     * @description Response model for list of connectors.
     */
    ConnectorListResponse: {
      /** Connectors */
      connectors: components["schemas"]["ConnectorResponse"][];
      /** Count */
      count: number;
    };
    /**
     * ConnectorResponse
     * @description Response model for connector data.
     */
    ConnectorResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Connector Type */
      connector_type: string;
      /** Status */
      status: string;
      /** Last Tested At */
      last_tested_at: string | null;
      /** Last Test Result */
      last_test_result: {
        [key: string]: unknown;
      } | null;
      /** Created At */
      created_at: string;
    };
    /**
     * ConnectorType
     * @description Type of external connector.
     * @enum {string}
     */
    ConnectorType: "catena_x" | "rest" | "file";
    /**
     * CreateDPPRequest
     * @description Request model for creating a new DPP.
     */
    CreateDPPRequest: {
      asset_ids: components["schemas"]["AssetIdsInput"];
      /**
       * Selected Templates
       * @description List of template keys to include
       * @default [
       *   "digital-nameplate"
       * ]
       */
      selected_templates?: string[];
      /** Initial Data */
      initial_data?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * DPPDetailResponse
     * @description Detailed response model including revision data.
     */
    DPPDetailResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
      /** Owner Subject */
      owner_subject: string;
      /** Asset Ids */
      asset_ids: {
        [key: string]: unknown;
      };
      /** Qr Payload */
      qr_payload: string | null;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
      /** Current Revision No */
      current_revision_no: number | null;
      /** Aas Environment */
      aas_environment: {
        [key: string]: unknown;
      } | null;
      /** Digest Sha256 */
      digest_sha256: string | null;
    };
    /**
     * DPPListResponse
     * @description Response model for list of DPPs.
     */
    DPPListResponse: {
      /** Dpps */
      dpps: components["schemas"]["DPPResponse"][];
      /** Count */
      count: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /**
     * DPPResponse
     * @description Response model for DPP data.
     */
    DPPResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
      /** Owner Subject */
      owner_subject: string;
      /** Asset Ids */
      asset_ids: {
        [key: string]: unknown;
      };
      /** Qr Payload */
      qr_payload: string | null;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
    };
    /**
     * DPPStatus
     * @description DPP lifecycle status.
     * @enum {string}
     */
    DPPStatus: "draft" | "published" | "archived";
    /**
     * GS1DigitalLinkResponse
     * @description Response model for GS1 Digital Link generation.
     */
    GS1DigitalLinkResponse: {
      /**
       * Dpp Id
       * Format: uuid
       */
      dpp_id: string;
      /**
       * Digital Link
       * @description GS1 Digital Link URL
       */
      digital_link: string;
      /**
       * Gtin
       * @description Global Trade Item Number
       */
      gtin: string;
      /**
       * Serial
       * @description Serial number
       */
      serial: string;
      /**
       * Resolver Url
       * @description GS1 resolver base URL
       */
      resolver_url: string;
    };
    /**
     * GlobalAssetIdBaseUriResponse
     * @description Response model for global asset ID base URI.
     */
    GlobalAssetIdBaseUriResponse: {
      /** Global Asset Id Base Uri */
      global_asset_id_base_uri: string;
    };
    /**
     * GlobalAssetIdBaseUriUpdateRequest
     * @description Request model for updating global asset ID base URI.
     */
    GlobalAssetIdBaseUriUpdateRequest: {
      /** Global Asset Id Base Uri */
      global_asset_id_base_uri: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * ImportDPPRequest
     * @description Request model for importing a DPP from JSON.
     */
    ImportDPPRequest: {
      [key: string]: unknown;
    };
    /**
     * MasterAliasesUpdateRequest
     * @description Request model for updating version aliases.
     */
    MasterAliasesUpdateRequest: {
      /** Aliases */
      aliases?: string[];
    };
    /**
     * MasterCreateRequest
     * @description Request model for creating a DPP master.
     */
    MasterCreateRequest: {
      /** Product Id */
      product_id: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Selected Templates */
      selected_templates?: string[];
      /** Asset Ids */
      asset_ids?: {
        [key: string]: unknown;
      } | null;
      /** Initial Data */
      initial_data?: {
        [key: string]: unknown;
      } | null;
      /** Template Json */
      template_json?: {
        [key: string]: unknown;
      } | null;
      /** Variables */
      variables?: components["schemas"]["MasterVariableInput"][] | null;
    };
    /**
     * MasterDetailResponse
     * @description Detailed master response including draft template.
     */
    MasterDetailResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Product Id */
      product_id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Selected Templates */
      selected_templates: string[];
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
      /** Draft Template Json */
      draft_template_json: {
        [key: string]: unknown;
      };
      /** Draft Variables */
      draft_variables: components["schemas"]["MasterVariableInput"][];
    };
    /**
     * MasterListResponse
     * @description Response model for listing masters.
     */
    MasterListResponse: {
      /** Masters */
      masters: components["schemas"]["MasterResponse"][];
      /** Count */
      count: number;
    };
    /**
     * MasterResponse
     * @description Response model for master metadata.
     */
    MasterResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Product Id */
      product_id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Selected Templates */
      selected_templates: string[];
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
    };
    /**
     * MasterUpdateRequest
     * @description Request model for updating a DPP master.
     */
    MasterUpdateRequest: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Selected Templates */
      selected_templates?: string[] | null;
      /** Asset Ids */
      asset_ids?: {
        [key: string]: unknown;
      } | null;
      /** Initial Data */
      initial_data?: {
        [key: string]: unknown;
      } | null;
      /** Template Json */
      template_json?: {
        [key: string]: unknown;
      } | null;
      /** Variables */
      variables?: components["schemas"]["MasterVariableInput"][] | null;
    };
    /**
     * MasterVariableInput
     * @description Variable definition for DPP master templates.
     */
    MasterVariableInput: {
      /** Name */
      name: string;
      /** Label */
      label?: string | null;
      /** Description */
      description?: string | null;
      /**
       * Required
       * @default true
       */
      required?: boolean;
      /** Default Value */
      default_value?: unknown;
      /**
       * Allow Default
       * @default true
       */
      allow_default?: boolean;
      /**
       * Expected Type
       * @default string
       */
      expected_type?: string;
      /** Constraints */
      constraints?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * MasterVariableResponse
     * @description Variable definition including resolved paths.
     */
    MasterVariableResponse: {
      /** Name */
      name: string;
      /** Label */
      label?: string | null;
      /** Description */
      description?: string | null;
      /**
       * Required
       * @default true
       */
      required?: boolean;
      /** Default Value */
      default_value?: unknown;
      /**
       * Allow Default
       * @default true
       */
      allow_default?: boolean;
      /**
       * Expected Type
       * @default string
       */
      expected_type?: string;
      /** Constraints */
      constraints?: {
        [key: string]: unknown;
      } | null;
      /** Paths */
      paths?: {
          [key: string]: string;
        }[];
    };
    /**
     * MasterVersionCreateRequest
     * @description Request model for releasing a master version.
     */
    MasterVersionCreateRequest: {
      /** Version */
      version: string;
      /** Aliases */
      aliases?: string[];
      /**
       * Update Latest
       * @default true
       */
      update_latest?: boolean;
    };
    /**
     * MasterVersionResponse
     * @description Response model for released master versions.
     */
    MasterVersionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Version */
      version: string;
      /** Aliases */
      aliases: string[];
      /** Status */
      status: string;
      /** Released At */
      released_at: string;
    };
    /**
     * PolicyCreateRequest
     * @description Request model for creating a policy.
     */
    PolicyCreateRequest: {
      /** Dpp Id */
      dpp_id?: string | null;
      policy_type: components["schemas"]["PolicyType"];
      /** Target */
      target: string;
      effect: components["schemas"]["PolicyEffect"];
      /** Rules */
      rules: {
        [key: string]: unknown;
      };
      /**
       * Priority
       * @default 0
       */
      priority?: number;
      /** Description */
      description?: string | null;
    };
    /**
     * PolicyEffect
     * @description Effect of a policy rule.
     * @enum {string}
     */
    PolicyEffect: "allow" | "deny" | "mask" | "hide" | "encrypt_required";
    /**
     * PolicyListResponse
     * @description Response model for list of policies.
     */
    PolicyListResponse: {
      /** Policies */
      policies: components["schemas"]["PolicyResponse"][];
      /** Count */
      count: number;
    };
    /**
     * PolicyResponse
     * @description Response model for policy data.
     */
    PolicyResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Dpp Id */
      dpp_id: string | null;
      /** Policy Type */
      policy_type: string;
      /** Target */
      target: string;
      /** Effect */
      effect: string;
      /** Rules */
      rules: {
        [key: string]: unknown;
      };
      /** Priority */
      priority: number;
      /** Description */
      description: string | null;
      /** Is Active */
      is_active: boolean;
      /** Created At */
      created_at: string;
    };
    /**
     * PolicyType
     * @description Type of access control policy.
     * @enum {string}
     */
    PolicyType: "route" | "submodel" | "element";
    /**
     * PublishResultResponse
     * @description Response model for DPP publish result.
     */
    PublishResultResponse: {
      /** Status */
      status: string;
      /** Action */
      action?: string | null;
      /** Shell Id */
      shell_id?: string | null;
      /** Error Message */
      error_message?: string | null;
    };
    /**
     * RevisionResponse
     * @description Response model for revision data.
     */
    RevisionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Revision No */
      revision_no: number;
      /** State */
      state: string;
      /** Digest Sha256 */
      digest_sha256: string;
      /** Created By Subject */
      created_by_subject: string;
      /** Created At */
      created_at: string;
    };
    /**
     * SubmodelDefinitionResponse
     * @description Response model for submodel definition AST per revision.
     */
    SubmodelDefinitionResponse: {
      /**
       * Dpp Id
       * Format: uuid
       */
      dpp_id: string;
      /** Template Key */
      template_key: string;
      /**
       * Revision Id
       * Format: uuid
       */
      revision_id: string;
      /** Revision No */
      revision_no: number;
      /** State */
      state: string;
      /** Definition */
      definition: {
        [key: string]: unknown;
      };
    };
    /**
     * TemplateDefinitionResponse
     * @description Response model for template definition AST.
     */
    TemplateDefinitionResponse: {
      /** Template Key */
      template_key: string;
      /** Definition */
      definition: {
        [key: string]: unknown;
      };
    };
    /**
     * TemplateListResponse
     * @description Response model for list of templates.
     */
    TemplateListResponse: {
      /** Templates */
      templates: components["schemas"]["TemplateResponse"][];
      /** Count */
      count: number;
    };
    /**
     * TemplatePackageResponse
     * @description Template package response for SAP integration.
     */
    TemplatePackageResponse: {
      /** Master Id */
      master_id: string;
      /** Product Id */
      product_id: string;
      /** Name */
      name: string;
      /** Version */
      version: string;
      /** Aliases */
      aliases: string[];
      /** Template String */
      template_string: string;
      /** Variables */
      variables: components["schemas"]["MasterVariableResponse"][];
    };
    /**
     * TemplateResponse
     * @description Response model for template data.
     */
    TemplateResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Template Key */
      template_key: string;
      /** Idta Version */
      idta_version: string;
      /** Semantic Id */
      semantic_id: string;
      /** Source Url */
      source_url: string;
      /** Fetched At */
      fetched_at: string;
    };
    /** TenantCreateRequest */
    TenantCreateRequest: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
    };
    /** TenantListResponse */
    TenantListResponse: {
      /** Tenants */
      tenants: components["schemas"]["TenantResponse"][];
      /** Count */
      count: number;
    };
    /** TenantMemberListResponse */
    TenantMemberListResponse: {
      /** Members */
      members: components["schemas"]["TenantMemberResponse"][];
      /** Count */
      count: number;
    };
    /** TenantMemberRequest */
    TenantMemberRequest: {
      /** User Subject */
      user_subject: string;
      /** @default viewer */
      role?: components["schemas"]["TenantRole"];
    };
    /** TenantMemberResponse */
    TenantMemberResponse: {
      /** User Subject */
      user_subject: string;
      /** Role */
      role: string;
      /** Created At */
      created_at: string;
    };
    /** TenantMembershipListResponse */
    TenantMembershipListResponse: {
      /** Tenants */
      tenants: components["schemas"]["TenantMembershipResponse"][];
      /** Count */
      count: number;
    };
    /** TenantMembershipResponse */
    TenantMembershipResponse: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Role */
      role: string;
    };
    /** TenantResponse */
    TenantResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Created At */
      created_at: string;
      /** Updated At */
      updated_at: string;
    };
    /**
     * TenantRole
     * @description Roles scoped to a tenant.
     * @enum {string}
     */
    TenantRole: "viewer" | "publisher" | "tenant_admin";
    /**
     * TenantStatus
     * @description Lifecycle status for tenants.
     * @enum {string}
     */
    TenantStatus: "active" | "disabled";
    /** TenantUpdateRequest */
    TenantUpdateRequest: {
      /** Name */
      name?: string | null;
      status?: components["schemas"]["TenantStatus"] | null;
    };
    /**
     * TestResultResponse
     * @description Response model for connector test result.
     */
    TestResultResponse: {
      /** Status */
      status: string;
      /** Error Message */
      error_message?: string | null;
      /** Dtr Url */
      dtr_url?: string | null;
      /** Auth Type */
      auth_type?: string | null;
    };
    /**
     * UISchemaResponse
     * @description Response model for UI schema.
     */
    UISchemaResponse: {
      /** Template Key */
      template_key: string;
      /** Schema */
      schema: {
        [key: string]: unknown;
      };
    };
    /**
     * UpdateSubmodelRequest
     * @description Request model for updating a submodel.
     */
    UpdateSubmodelRequest: {
      /** Template Key */
      template_key: string;
      /** Data */
      data: {
        [key: string]: unknown;
      };
      /**
       * Rebuild From Template
       * @default false
       */
      rebuild_from_template?: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health Check */
  health_check_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /**
   * List My Tenants
   * @description List tenants the current user belongs to.
   */
  list_my_tenants_api_v1_tenants_mine_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantMembershipListResponse"];
        };
      };
    };
  };
  /**
   * List Tenants
   * @description List all tenants (platform admin).
   */
  list_tenants_api_v1_tenants_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantListResponse"];
        };
      };
    };
  };
  /**
   * Create Tenant
   * @description Create a new tenant (platform admin).
   */
  create_tenant_api_v1_tenants_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TenantCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TenantResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Tenant
   * @description Get tenant details (tenant member).
   */
  get_tenant_api_v1_tenants__tenant_slug__get: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Tenant
   * @description Update tenant metadata (platform admin).
   */
  update_tenant_api_v1_tenants__tenant_slug__patch: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TenantUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Members
   * @description List members of a tenant (tenant admin).
   */
  list_members_api_v1_tenants__tenant_slug__members_get: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantMemberListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Add Member
   * @description Add a member to a tenant (tenant admin).
   */
  add_member_api_v1_tenants__tenant_slug__members_post: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TenantMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TenantMemberResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Remove Member
   * @description Remove a member from a tenant (tenant admin).
   */
  remove_member_api_v1_tenants__tenant_slug__members__user_subject__delete: {
    parameters: {
      path: {
        user_subject: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Template Definition
   * @description Get the template definition AST (BaSyx parsed).
   *
   * Returns a stable representation of the submodel template tree.
   */
  get_template_definition_api_v1_templates__template_key__definition_get: {
    parameters: {
      path: {
        template_key: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TemplateDefinitionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Templates
   * @description List all registered templates.
   *
   * Returns all DPP4.0 templates that have been fetched and cached.
   */
  list_templates_api_v1_templates_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TemplateListResponse"];
        };
      };
    };
  };
  /**
   * Get Template
   * @description Get a specific template by key.
   *
   * Optionally specify a version, otherwise returns the pinned version.
   */
  get_template_api_v1_templates__template_key__get: {
    parameters: {
      query?: {
        version?: string | null;
      };
      path: {
        template_key: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TemplateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Template Ui Schema
   * @description Get the UI schema for a template.
   *
   * Returns a JSON Schema compatible structure for form rendering.
   */
  get_template_ui_schema_api_v1_templates__template_key__schema_get: {
    parameters: {
      path: {
        template_key: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UISchemaResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Refresh Templates
   * @description Refresh all templates from IDTA repository.
   *
   * Requires publisher role. Fetches and updates all DPP4.0 templates.
   */
  refresh_templates_api_v1_templates_refresh_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TemplateListResponse"];
        };
      };
    };
  };
  /**
   * Refresh Template
   * @description Refresh a specific template from IDTA repository.
   *
   * Requires publisher role.
   */
  refresh_template_api_v1_templates_refresh__template_key__post: {
    parameters: {
      path: {
        template_key: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TemplateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Dpps
   * @description List DPPs accessible to the current user.
   *
   * Publishers see their own DPPs. Viewers see all published DPPs.
   */
  list_dpps_api_v1_tenants__tenant_slug__dpps_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["DPPStatus"] | null;
        limit?: number;
        offset?: number;
      };
      path: {
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DPPListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Dpp
   * @description Create a new Digital Product Passport.
   *
   * Requires publisher role. Creates a draft DPP with selected templates.
   */
  create_dpp_api_v1_tenants__tenant_slug__dpps_post: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDPPRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["DPPResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Import Dpp
   * @description Import a DPP from a JSON payload.
   *
   * Accepts a raw AAS environment JSON or an export payload with `aasEnvironment`.
   * Optionally validates against a released master version.
   */
  import_dpp_api_v1_tenants__tenant_slug__dpps_import_post: {
    parameters: {
      query?: {
        /** @description Validate against a master template by product ID */
        master_product_id?: string | null;
        /** @description Master version or alias */
        master_version?: string;
      };
      path: {
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportDPPRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["DPPResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Rebuild All Dpps
   * @description Refresh templates and rebuild submodels for all DPPs.
   *
   * Requires tenant admin role.
   */
  rebuild_all_dpps_api_v1_tenants__tenant_slug__dpps_rebuild_all_post: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BulkRebuildResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Dpp
   * @description Get a specific DPP by ID.
   *
   * Returns full DPP details including current revision AAS environment.
   */
  get_dpp_api_v1_tenants__tenant_slug__dpps__dpp_id__get: {
    parameters: {
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DPPDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Submodel
   * @description Update a submodel within a DPP.
   *
   * Creates a new revision with the updated data.
   */
  update_submodel_api_v1_tenants__tenant_slug__dpps__dpp_id__submodel_put: {
    parameters: {
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSubmodelRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RevisionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Submodel Definition
   * @description Get a submodel definition derived from a DPP revision environment.
   */
  get_submodel_definition_api_v1_tenants__tenant_slug__dpps__dpp_id__submodels__template_key__definition_get: {
    parameters: {
      query?: {
        /** @description latest or published */
        revision?: string | null;
        revision_id?: string | null;
      };
      path: {
        dpp_id: string;
        template_key: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SubmodelDefinitionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Publish Dpp
   * @description Publish a DPP, making it visible to viewers.
   */
  publish_dpp_api_v1_tenants__tenant_slug__dpps__dpp_id__publish_post: {
    parameters: {
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DPPResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Archive Dpp
   * @description Archive a DPP, marking it as no longer active.
   */
  archive_dpp_api_v1_tenants__tenant_slug__dpps__dpp_id__archive_post: {
    parameters: {
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DPPResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Revisions
   * @description List all revisions for a DPP.
   *
   * Requires publisher role and ownership.
   */
  list_revisions_api_v1_tenants__tenant_slug__dpps__dpp_id__revisions_get: {
    parameters: {
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RevisionResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Masters */
  list_masters_api_v1_tenants__tenant_slug__masters_get: {
    parameters: {
      query?: {
        /** @description Filter by product ID */
        product_id?: string | null;
        limit?: number;
        offset?: number;
      };
      path: {
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MasterListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Master */
  create_master_api_v1_tenants__tenant_slug__masters_post: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MasterCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["MasterResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Master */
  get_master_api_v1_tenants__tenant_slug__masters__master_id__get: {
    parameters: {
      path: {
        master_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MasterDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Master */
  update_master_api_v1_tenants__tenant_slug__masters__master_id__patch: {
    parameters: {
      path: {
        master_id: string;
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MasterUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MasterDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Release Master Version */
  release_master_version_api_v1_tenants__tenant_slug__masters__master_id__versions_post: {
    parameters: {
      path: {
        master_id: string;
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MasterVersionCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["MasterVersionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Master Aliases */
  update_master_aliases_api_v1_tenants__tenant_slug__masters__master_id__versions__version__aliases_patch: {
    parameters: {
      path: {
        master_id: string;
        version: string;
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MasterAliasesUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MasterVersionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Template By Product */
  get_template_by_product_api_v1_tenants__tenant_slug__masters_by_product__product_id__versions__version__template_get: {
    parameters: {
      path: {
        product_id: string;
        version: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TemplatePackageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Variables By Product */
  get_variables_by_product_api_v1_tenants__tenant_slug__masters_by_product__product_id__versions__version__variables_get: {
    parameters: {
      path: {
        product_id: string;
        version: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MasterVariableResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Policies
   * @description List all policies.
   *
   * Requires publisher role. Can filter by DPP ID or policy type.
   */
  list_policies_api_v1_tenants__tenant_slug__policies_get: {
    parameters: {
      query?: {
        /** @description Filter by DPP ID */
        dpp_id?: string | null;
        /** @description Filter by policy type */
        policy_type?: components["schemas"]["PolicyType"] | null;
      };
      path: {
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Policy
   * @description Create a new policy.
   *
   * Requires admin role.
   */
  create_policy_api_v1_tenants__tenant_slug__policies_post: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PolicyCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PolicyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Policy
   * @description Get a specific policy by ID.
   */
  get_policy_api_v1_tenants__tenant_slug__policies__policy_id__get: {
    parameters: {
      path: {
        policy_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Policy
   * @description Delete a policy.
   *
   * Requires admin role.
   */
  delete_policy_api_v1_tenants__tenant_slug__policies__policy_id__delete: {
    parameters: {
      path: {
        policy_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Connectors
   * @description List all connectors.
   *
   * Requires publisher role.
   */
  list_connectors_api_v1_tenants__tenant_slug__connectors_get: {
    parameters: {
      query?: {
        /** @description Filter by connector type */
        connector_type?: components["schemas"]["ConnectorType"] | null;
      };
      path: {
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ConnectorListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Connector
   * @description Create a new Catena-X connector.
   *
   * Config should include:
   * - dtr_base_url: DTR API base URL
   * - auth_type: "oidc" or "token"
   * - client_id, client_secret (for OIDC)
   * - token (for token auth)
   * - bpn: Business Partner Number
   * - submodel_base_url: URL where submodels are exposed
   * - edc_dsp_endpoint: Optional EDC DSP endpoint
   */
  create_connector_api_v1_tenants__tenant_slug__connectors_post: {
    parameters: {
      path: {
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConnectorCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ConnectorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Connector
   * @description Get a specific connector by ID.
   */
  get_connector_api_v1_tenants__tenant_slug__connectors__connector_id__get: {
    parameters: {
      path: {
        connector_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ConnectorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Test Connector
   * @description Test connectivity for a connector.
   *
   * Verifies DTR endpoint is reachable and authentication is valid.
   */
  test_connector_api_v1_tenants__tenant_slug__connectors__connector_id__test_post: {
    parameters: {
      path: {
        connector_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TestResultResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Publish Dpp To Connector
   * @description Publish a DPP to a connector's Digital Twin Registry.
   *
   * The DPP must be published first. Creates or updates
   * the shell descriptor in the DTR.
   */
  publish_dpp_to_connector_api_v1_tenants__tenant_slug__connectors__connector_id__publish__dpp_id__post: {
    parameters: {
      path: {
        connector_id: string;
        dpp_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PublishResultResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Export Dpp
   * @description Export a DPP in the specified format.
   *
   * Supported formats:
   * - json: AAS Environment JSON with metadata
   * - aasx: AASX package (IDTA Part 5 compliant)
   * - pdf: PDF summary
   */
  export_dpp_api_v1_tenants__tenant_slug__export__dpp_id__get: {
    parameters: {
      query?: {
        /** @description Export format */
        format?: "json" | "aasx" | "pdf";
      };
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Qr Code
   * @description Generate a QR code for a DPP.
   *
   * The QR code contains the DPP viewer URL for product identification.
   */
  generate_qr_code_api_v1_tenants__tenant_slug__qr__dpp_id__get: {
    parameters: {
      query?: {
        /** @description Image format */
        format?: "png" | "svg";
        /** @description Image size in pixels */
        size?: number;
      };
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Carrier
   * @description Generate a customized data carrier for a DPP.
   *
   * Supports QR codes and GS1 Digital Link format with configurable
   * colors, size, and output format (PNG, SVG, PDF).
   */
  generate_carrier_api_v1_tenants__tenant_slug__qr__dpp_id__carrier_post: {
    parameters: {
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CarrierRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CarrierResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Gs1 Digital Link
   * @description Get the GS1 Digital Link URL for a DPP.
   *
   * Returns the GS1 Digital Link format URL that can be encoded
   * in a QR code for EU DPP/ESPR compliance.
   */
  get_gs1_digital_link_api_v1_tenants__tenant_slug__qr__dpp_id__gs1_get: {
    parameters: {
      path: {
        dpp_id: string;
        tenant_slug: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GS1DigitalLinkResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Global Asset Id Base Uri
   * @description Get the current global asset ID base URI.
   *
   * Requires admin role.
   */
  get_global_asset_id_base_uri_api_v1_admin_settings_global_asset_id_base_uri_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GlobalAssetIdBaseUriResponse"];
        };
      };
    };
  };
  /**
   * Update Global Asset Id Base Uri
   * @description Update the global asset ID base URI.
   *
   * Requires admin role.
   */
  update_global_asset_id_base_uri_api_v1_admin_settings_global_asset_id_base_uri_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GlobalAssetIdBaseUriUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GlobalAssetIdBaseUriResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
