/* eslint-disable */
// This file is auto-generated by scripts/generate-cirpass-stories.mjs
import type { CirpassLabManifest } from './schema/storySchema';

export const generatedCirpassManifest: CirpassLabManifest = {
  "manifest_version": "v1.0.0",
  "story_version": "V3.1",
  "generated_at": "2026-02-14T00:00:00Z",
  "source_status": "fresh",
  "stories": [
    {
      "id": "core-loop-v3_1",
      "title": "CIRPASS Core Lifecycle Loop",
      "summary": "Guided CREATE→ACCESS→UPDATE→TRANSFER→DEACTIVATE walkthrough with technical transparency.",
      "personas": [
        "Manufacturer",
        "Consumer",
        "Repairer",
        "Recycler",
        "Authority"
      ],
      "learning_goals": [
        "Issue and validate required DPP payload attributes.",
        "Apply role-based access filtering and restricted field controls.",
        "Preserve lifecycle integrity while updates and transfer events occur.",
        "Close end-of-life and recover circularity intelligence."
      ],
      "preconditions_md": "This simulation uses synthetic payloads and deterministic sandbox logic.\nFor live mode, a lab tenant reset + seed is required.\n",
      "references": [
        {
          "label": "CIRPASS project results",
          "ref": "https://cirpassproject.eu/project-results/"
        },
        {
          "label": "Zenodo record 17979585",
          "ref": "https://zenodo.org/records/17979585"
        }
      ],
      "version": "V3.1",
      "last_reviewed": "2026-02-14",
      "steps": [
        {
          "id": "create-passport",
          "level": "create",
          "title": "CREATE passport payload",
          "actor": "Manufacturer",
          "intent": "Compose mandatory fields for an ESPR-aligned passport.",
          "explanation_md": "Add identifier, material composition, and carbon footprint before publication.",
          "ui_action": {
            "label": "Validate & Continue",
            "kind": "form"
          },
          "api": {
            "method": "POST",
            "path": "/api/v1/public/cirpass/stories/latest",
            "auth": "none",
            "expected_status": 200,
            "request_example": {
              "identifier": "did:web:dpp.eu:product:demo-bike",
              "materialComposition": "recycled_aluminum",
              "carbonFootprint": 14.2
            },
            "response_example": {
              "status": "accepted"
            }
          },
          "artifacts": {
            "before": {
              "status": "draft",
              "payload": {}
            },
            "after": {
              "status": "active",
              "payload": {
                "identifier": "did:web:dpp.eu:product:demo-bike",
                "materialComposition": "recycled_aluminum",
                "carbonFootprint": 14.2
              }
            },
            "diff_hint": "Mandatory fields become available to the technical layer."
          },
          "checks": [
            {
              "type": "schema",
              "expression": "required:create_fields",
              "expected": [
                "identifier",
                "materialComposition",
                "carbonFootprint"
              ]
            }
          ],
          "policy": {
            "required_role": "publisher",
            "opa_policy": "dpp/authz",
            "expected_decision": "allow",
            "note": "Manufacturer workflow may write payload metadata."
          },
          "variants": [
            "happy"
          ]
        },
        {
          "id": "access-routing",
          "level": "access",
          "title": "ACCESS policy routing",
          "actor": "Authority",
          "intent": "Route consumer and authority access with restricted fields masked for consumers.",
          "explanation_md": "Access logic should deny restricted data to non-authority actors.",
          "ui_action": {
            "label": "Validate & Continue",
            "kind": "select"
          },
          "api": {
            "method": "GET",
            "path": "/api/v1/public/dpps/{id}",
            "auth": "none",
            "expected_status": 200,
            "response_example": {
              "publicFields": [
                "manual",
                "safety"
              ]
            }
          },
          "checks": [
            {
              "type": "status",
              "expected": 200
            }
          ],
          "policy": {
            "required_role": "authority",
            "opa_policy": "dpp/authz",
            "expected_decision": "deny",
            "note": "Consumer path must not expose restricted fields."
          },
          "variants": [
            "happy",
            "unauthorized",
            "not_found"
          ]
        },
        {
          "id": "update-repair-chain",
          "level": "update",
          "title": "UPDATE repair chain",
          "actor": "Repairer",
          "intent": "Append a lifecycle event while preserving hash-chain integrity.",
          "explanation_md": "The new event hash must differ from prior hash and include a repair event narrative.",
          "ui_action": {
            "label": "Validate & Continue",
            "kind": "form"
          },
          "api": {
            "method": "PATCH",
            "path": "/api/v1/tenants/{tenant}/dpps/{id}",
            "auth": "user",
            "expected_status": 200
          },
          "checks": [
            {
              "type": "jsonpath",
              "expression": "$.repairEvent",
              "expected": "present"
            }
          ],
          "policy": {
            "required_role": "publisher",
            "opa_policy": "dpp/authz",
            "expected_decision": "allow"
          },
          "variants": [
            "happy"
          ]
        },
        {
          "id": "transfer-handoff",
          "level": "transfer",
          "title": "TRANSFER ownership handoff",
          "actor": "Retailer",
          "intent": "Transfer ownership while preserving confidentiality boundaries.",
          "explanation_md": "From/to actors must differ and confidentiality constraints remain enabled.",
          "ui_action": {
            "label": "Validate & Continue",
            "kind": "form"
          },
          "api": {
            "method": "POST",
            "path": "/api/v1/tenants/{tenant}/shares",
            "auth": "user",
            "expected_status": 201
          },
          "checks": [
            {
              "type": "status",
              "expected": 201
            }
          ],
          "policy": {
            "required_role": "publisher",
            "opa_policy": "dpp/authz",
            "expected_decision": "allow"
          },
          "variants": [
            "happy"
          ]
        },
        {
          "id": "deactivate-loop",
          "level": "deactivate",
          "title": "DEACTIVATE and circular loop closure",
          "actor": "Recycler",
          "intent": "Mark end-of-life and expose recovered material outputs.",
          "explanation_md": "End-of-life state requires recovered materials and next-passport spawn flag.",
          "ui_action": {
            "label": "Validate & Continue",
            "kind": "form"
          },
          "api": {
            "method": "POST",
            "path": "/api/v1/public/cirpass/leaderboard/submit",
            "auth": "none",
            "expected_status": 200
          },
          "checks": [
            {
              "type": "jsonpath",
              "expression": "$.status",
              "expected": "end_of_life"
            }
          ],
          "policy": {
            "required_role": "recycler",
            "opa_policy": "dpp/authz",
            "expected_decision": "allow"
          },
          "variants": [
            "happy"
          ]
        }
      ]
    }
  ],
  "feature_flags": {
    "scenario_engine_enabled": true,
    "live_mode_enabled": false,
    "inspector_enabled": true
  }
};
